void DisplayMenu();
void AddToStack();
void RemoveFromStack();
void DisplayStack();
void ClearStack();
void ExitProgram();
void ClearConsole();
void Pause();
void Pause(float seconds);
void DisplayHelp();
void DebugMemory(stack* pila);
